backend:
  name: git-gateway

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "players"
    label: "Players"
    folder: "players"
    format: "json"
    identifier_field: name
    create: true
    slug: "{{slug}}"
    fields:
      # - {label: "ID", name: "id", widget: "id"}
      - {label: "ID", name: "id", widget: "testWidget"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Photo", name: "photo", widget: "image"}
  - name: "matches"
    label: "Matches"
    folder: "matches"
    format: "json"
    create: true
    identifier_field: id
    fields: 
      - label: "ID"
        name: "id"
        widget: "datetime"
        dateFormat: "x"
        timeFormat: ""
        format: "x"
      - label: "Player 1"
        name: "player1"
        widget: "object"
        fields:
          - label: "Player"
            name: "player"
            widget: "relation"
            collection: "players"
            searchFields: ['name']
            displayFields: ['name']
            valueField: "id"
          - label: "Score"
            name: "score"
            widget: "number"
            min: 0
            max: 3
      - label: "Player 2"
        name: "player2"
        widget: "object"
        fields:
          - label: "Player"
            name: "player"
            widget: "relation"
            collection: "players"
            searchFields: ['name']
            displayFields: ['name']
            valueField: "id"
          - label: "Score"
            name: "score"
            widget: "number"
            min: 0
            max: 3