backend:
  name: git-gateway

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "players"
    label: "Players"
    folder: "players"
    format: "json"
    identifier_field: name
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "ID", name: "id", widget: "id"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Photo", name: "photo", widget: "image"}
  - name: "matches"
    label: "Matches"
    folder: "matches"
    format: "json"
    create: true
    identifier_field: id
    fields: 
      - { label: "ID", name: "id", widget: "id" }
      - label: "Player 1"
        name: "player1"
        widget: "relation"
        collection: "players"
        searchFields: ['name']
        displayFields: ['name']
        valueField: "id"
      - label: "Player 1 Score"
        name: "player1Score"
        widget: "number"
        min: 0
        max: 3
      - label: "Player 2"
        name: "player2"
        widget: "relation"
        collection: "players"
        searchFields: ['name']
        displayFields: ['name']
        valueField: "id"
      - label: "Player 2 Score"
        name: "player2Score"
        widget: "number"
        min: 0
        max: 3