backend:
  name: git-gateway

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "players"
    label: "Players"
    folder: "players"
    format: "json"
    identifier_field: name
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "ID", name: "id", widget: "id"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Photo", name: "photo", widget: "image"}
  - name: "seasons"
    label: "Seasons"
    folder: "seasons"
    format: "json"
    create: true
    slug: "{{slug}}"
    fields: 
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Fixtures"
        name: "fixtures"
        widget: "list"
        required: false
        fields:
          - label: "Player 1"
            name: "player1"
            widget: "relation"
            collection: "players"
            searchFields: ['name']
            displayFields: ['name']
            valueField: "id"
          - { label: "Player 1 Score", name: "player1Score", widget: "number", default: 0, valueType: int, required: false }
          - label: "Player 2"
            name: "player2"
            widget: "relation"
            collection: "players"
            searchFields: ['name']
            displayFields: ['name']
            valueField: "id"
          - { label: "Player 2 Score", name: "player2Score", widget: "number", default: 0, valueType: int, required: false }
      - label: "Date Created"
        name: "dateCreated"
        widget: "datetime"