backend:
  name: github
  repo: hitmarkerjobs/pool

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "players"
    label: "Players"
    folder: "players"
    identifier_field: name
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - label: "Photo"
        name: "photo"
        widget: "image"
