backend:
  name: git-gateway

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "players"
    label: "Players"
    folder: "players"
    format: "json"
    identifier_field: name
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Photo", name: "photo", widget: "image"}
  - name: "seasons"
    label: "Seasons"
    folder: "seasons"
    format: "json"
    create: true
    slug: "{{slug}}"
    fields: 
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Matches"
        name: "matches"
        widget: "list"
        fields:
          - label: Fixture
            name: fixture
            widget: object
            fields:
              - { label: "Player 1 Score", name: "player1Score", widget: "number", min: 0 }
              - { label: "Player 2 Score", name: "player2Score", widget: "number", min: 0 }